use_frameworks!

target 'Canary_Example' do
  platform :ios, '9.0' 
  pod 'Canary/Swift', :path => '../'

  target 'Canary_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
    pod 'Nimble-Snapshots' , '~> 6.3.0'
  end
end

target 'Canary_Exampe_OC' do
  platform :ios, '9.0'
  pod 'Canary', :path => '../'
end

target 'Canary_Example_macOS' do
  platform :osx, '10.11'
  pod 'Canary/Swift', :path => '../'
end

post_install do |installer|
  require_relative '../Sources/Canary/ProjectConfigurator.rb'
  ProjectConfigurator::configure_project(installer, 'com.binaryparadise.neverland', 'https://y.neverland.life')
end
