use_frameworks!
use_modular_headers!

target 'Canary_Example_macOS' do
  platform :osx, '10.13'
  pod 'Canary/Swift', :path => '../'
end

post_install do |installer|
  require_relative '../Sources/Canary/ProjectConfigurator.rb'
  ProjectConfigurator::configure_project(installer, 'com.binaryparadise.neverland', 'http://127.0.0.1:8081')
end
